# -*- coding: utf-8 -*-
"""Perceptron-00

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANk4Bcw3g7ftsn8NLq8DTZWKSrJ3GtFS
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('placement.csv', index_col=0)
df

sns.scatterplot(data=df, x="cgpa", y="iq", hue="placement")
plt.title('CGPA vs IQ by Placement Status')
plt.xlabel('CGPA')
plt.ylabel('IQ')
plt.show()

# Now implement the perceptron
# We can imagine a line, while formimg the line it will calculate the weights(w1,w2) and the bias

x = df.iloc[:,0:2]

y = df.iloc[:,-1]

# Import the perceptron from the sklearn library
from sklearn.linear_model import Perceptron
p = Perceptron()

p.fit(x,y)

# To retreive the value of w1 and w2 and b run the following commands
w = p.coef_
b = p.intercept_

# To see how the line separates the two labels (Placed or not placed)
from mlxtend.plotting import plot_decision_regions
plot_decision_regions(x.values, y.values, clf=p)
plt.xlabel('CGPA')
plt.ylabel('Resume Score')
plt.show()


